### ISSUE TITLE
Powerpoint 1

### ISSUE THREAD

**Issue by KershawK5646** [KershawK5646/CapstoneProject#7]
Powerpoint for presentation 1

**Comment by praterj5446** [comment]
Right now I have a powerpoint added, it is only really the title slide. I am writing out a outline then I will make more slides and title the slides for what they should be.

**Comment by praterj5446** [comment]
The presentation now has slides titled to what we need. I just need the information and diagrams to continue the powerpoint.

**Comment by praterj5446** [comment]
Layout for the PowerPoint is mostly complete, need some information, a couple of diagrams, then the PowerPoint will be complete.

**Comment by praterj5446** [comment]
A slide was deleted, I do still need a couple of the diagrams.

**Comment by praterj5446** [comment]
A couple more slides were deleted, but I did add a total of 6 blank slides.

**Comment by praterj5446** [comment]
More information has been added to the powerpoint.

**Comment by biglerd7304** [comment]
I added to a slide

**Comment by praterj5446** [comment]
Final touches will be done once everyone has added there part to the slides.

**Comment by KershawK5646** [comment]
Added my portion  containing code. 
Adjusted other pages to shorten word count
